#!/usr/bin/env python3
"""
Compute per-task accuracy delta between ExRD (full method) and the no-RD
ablation (proportional replay only), using the final-stage row of each run's
task_summary.csv.

Outputs:
  - A formatted table to stdout.
  - A LaTeX-ready row block to <out_dir>/rd_per_task_delta.tex.
  - A CSV of the deltas to <out_dir>/rd_per_task_delta.csv.

Usage:
  python mtil/scripts/compute_rd_per_task_delta.py
  python mtil/scripts/compute_rd_per_task_delta.py \
      --exrd-csv mtil/ckpt/11task/phase3_no_lora_v4/task_summary.csv \
      --nord-csv mtil/ckpt/11task/ablation_prop_replay/task_summary.csv \
      --out-dir  mtil/ckpt/11task/rd_delta
"""

import argparse
import csv
import os
import sys

DEFAULT_TASKS = [
    "Aircraft", "Caltech101", "CIFAR100", "DTD", "EuroSAT", "Flowers",
    "Food", "MNIST", "OxfordPet", "StanfordCars", "SUN397", "ImageNet",
]


def last_row(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        sys.exit(f"error: no rows in {path}")
    return rows[-1]


def fmt_delta(d):
    return f"{d:+.2f}" if abs(d) >= 0.005 else "+0.00"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--exrd-csv",
        default="mtil/ckpt/11task/phase3_no_lora_v4/task_summary.csv",
        help="task_summary.csv for the full ExRD run",
    )
    p.add_argument(
        "--nord-csv",
        default="mtil/ckpt/11task/ablation_prop_replay/task_summary.csv",
        help="task_summary.csv for the no-RD ablation (proportional replay only)",
    )
    p.add_argument(
        "--out-dir",
        default="mtil/ckpt/11task/rd_delta",
        help="directory to write the LaTeX and CSV outputs",
    )
    p.add_argument(
        "--tasks",
        nargs="+",
        default=DEFAULT_TASKS,
        help="evaluation columns to report, in order",
    )
    args = p.parse_args()

    exrd = last_row(args.exrd_csv)
    nord = last_row(args.nord_csv)

    rows = []
    for t in args.tasks:
        if t not in exrd or t not in nord:
            print(f"warning: column {t!r} missing from one of the CSVs; skipping",
                  file=sys.stderr)
            continue
        e, n = float(exrd[t]), float(nord[t])
        rows.append((t, e, n, e - n))

    # stdout table
    print(f"{'Task':<15} {'ExRD':>8} {'no-RD':>8} {'Delta':>8}")
    print("-" * 41)
    for t, e, n, d in rows:
        print(f"{t:<15} {e:>8.2f} {n:>8.2f} {fmt_delta(d):>8}")
    print("-" * 41)
    mean_delta = sum(d for _, _, _, d in rows) / len(rows)
    print(f"{'mean':<15} {'':>8} {'':>8} {fmt_delta(mean_delta):>8}")

    # outputs
    os.makedirs(args.out_dir, exist_ok=True)

    csv_path = os.path.join(args.out_dir, "rd_per_task_delta.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["task", "exrd", "no_rd", "delta"])
        for t, e, n, d in rows:
            w.writerow([t, f"{e:.4f}", f"{n:.4f}", f"{d:.4f}"])

    tex_path = os.path.join(args.out_dir, "rd_per_task_delta.tex")
    with open(tex_path, "w") as f:
        f.write("% Auto-generated by mtil/scripts/compute_rd_per_task_delta.py\n")
        f.write("% Paste into the appendix table body.\n")
        for t, e, n, d in rows:
            sign = "$+$" if d >= 0 else "$-$"
            f.write(f"{t:<14} & {e:6.2f} & {n:6.2f} & {sign}{abs(d):.2f} \\\\\n")

    print()
    print(f"wrote {csv_path}")
    print(f"wrote {tex_path}")


if __name__ == "__main__":
    main()
