#!/usr/bin/env python3
"""
Summarise several runs into one Last / Avg / Transfer table — the control table
for Reviewer zvRY's Q2 and Q3.

Metric definitions match mtil/scripts/compute_metrics.py:
  Last     mean over the 11 trained tasks in the final row
  Avg      mean of the diagonal (accuracy on task t right after training t)
  Transfer mean of the held-out ImageNet column across all stages

Usage (from the repo root) — with default paths:

    python mtil/scripts/rebuttal/rd_control_table.py

or explicitly, one LABEL=PATH per run:

    python mtil/scripts/rebuttal/rd_control_table.py \
        "ExRD (RD on replay, frozen teacher)=mtil/ckpt/11task/phase3_no_lora_v4/task_summary.csv" \
        "RD on current-task images=mtil/ckpt/11task/rebuttal_rd_current_images/task_summary.csv"

Missing runs are reported as "not finished" rather than skipped silently, so an
in-progress rebuttal table never looks complete when it is not.
"""

import argparse
import csv
import os
import sys

HELD_OUT = "ImageNet"
META_COLS = {"task_idx", "task_name", "avg"}

DEFAULT_RUNS = [
    ("ExRD (RD on replay, frozen teacher)",
     "mtil/ckpt/11task/phase3_no_lora_v4/task_summary.csv"),
    ("Replay only, lambda=0 (iteration-matched)",
     "mtil/ckpt/11task/rebuttal_replay_only_matched/task_summary.csv"),
    ("RD on current-task images (C1)",
     "mtil/ckpt/11task/rebuttal_rd_current_images/task_summary.csv"),
    ("RD teacher = previous-task ckpt (C2)",
     "mtil/ckpt/11task/rebuttal_rd_prev_teacher/task_summary.csv"),
    ("RD on reference images (C3)",
     "mtil/ckpt/11task/rebuttal_rd_reference_images/task_summary.csv"),
    ("Replay only, lambda=0 (uniform 1500 it.)",
     "mtil/ckpt/11task/ablation_prop_replay/task_summary.csv"),
    ("ZSCL only, no replay",
     "mtil/ckpt/11task/ablation_zscl_only/task_summary.csv"),
]


def metrics(path):
    """Return (last, avg, transfer, n_stages) or None if the run is unavailable."""
    if not os.path.exists(path):
        return None
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return None

    task_cols = [c for c in rows[0] if c not in META_COLS and c != HELD_OUT]

    diag = [float(r[c]) for r in rows for c in [r["task_name"]]
            if c in task_cols and r.get(c)]
    last = [float(rows[-1][c]) for c in task_cols if rows[-1].get(c)]
    transfer = [float(r[HELD_OUT]) for r in rows if r.get(HELD_OUT)]

    return (
        sum(last) / len(last) if last else None,
        sum(diag) / len(diag) if diag else None,
        sum(transfer) / len(transfer) if transfer else None,
        len(rows),
    )


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("runs", nargs="*", metavar="LABEL=PATH",
                   help="runs to include; defaults to the rebuttal set")
    p.add_argument("--expected-stages", type=int, default=11,
                   help="stages a complete 11-task run should have (default: 11)")
    p.add_argument("--tex", default=None, help="also write a LaTeX table body here")
    args = p.parse_args()

    runs = []
    for spec in args.runs:
        if "=" not in spec:
            sys.exit(f"error: expected LABEL=PATH, got {spec!r}")
        label, path = spec.split("=", 1)
        runs.append((label, path))
    if not runs:
        runs = DEFAULT_RUNS

    width = max(len(label) for label, _ in runs)
    header = f"{'Run':<{width}}  {'Last':>7} {'Avg':>7} {'Transfer':>9}  {'stages':>6}"
    print()
    print(header)
    print("-" * len(header))

    results = []
    for label, path in runs:
        m = metrics(path)
        results.append((label, path, m))
        if m is None:
            print(f"{label:<{width}}  {'not finished / missing':>26}   ({path})")
            continue
        last, avg, transfer, stages = m
        flag = "" if stages >= args.expected_stages else f"  <-- only {stages} stages"
        print(f"{label:<{width}}  {last:>7.2f} {avg:>7.2f} {transfer:>9.2f}  {stages:>6d}{flag}")
    print("-" * len(header))

    done = [r for r in results if r[2] is not None]
    print(f"{len(done)}/{len(results)} runs available")

    if args.tex:
        os.makedirs(os.path.dirname(os.path.abspath(args.tex)) or ".", exist_ok=True)
        with open(args.tex, "w") as f:
            f.write("% Auto-generated by mtil/scripts/rebuttal/rd_control_table.py\n")
            for label, _, m in results:
                if m is None:
                    f.write(f"% {label}: run not finished\n")
                    continue
                last, avg, transfer, _ = m
                f.write(f"{label} & {last:.2f} & {avg:.2f} & {transfer:.2f} \\\\\n")
        print(f"wrote {args.tex}")


if __name__ == "__main__":
    main()
